service:
  name: service-product-reviews
image:
  repository: 952893849914.dkr.ecr.us-east-1.amazonaws.com/aicares-application/product-reviews
containerPort: 3551
resources:
  limits:
    memory: "100Mi"
  requests:
    memory: "32Mi"
    cpu: "50m"
env:
  - name: PRODUCT_REVIEWS_PORT
    value: "3551"
  - name: OTEL_SERVICE_NAME
    value: "product-reviews"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector:4317"
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
  - name: DB_CONNECTION_STRING
    value: "host=postgresql user=astronomy_user password=astronomy_password dbname=astronomy_db"
